### ISSUE TITLE
Feature 1: User can find a place on a map

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can find a place on a map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type in a place in a provided input box to search for a place and once a place is selected, will place a marker on the map for that place

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/189774763-4319ef6c-d545-497a-892e-14de89024a34.png)
![image](https://user-images.githubusercontent.com/106636383/189774799-ad6db915-3b73-4a07-8be6-c67366ac5f6e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

- [x] implement Google Maps
   - [x] this will be in the main app.jsx to always render the map on a page
   - [x] import the JS function Google Maps to display it full width and full height of the screen
   - [x] get user's current coordinates in order to display the map centered around user's location.
- [x] implement Google Places
   - [x] will be in the main app.jsx, the input text will always shows on a page.
   - [x] import the JS function Google Places to have it show.
- [x] add marker to the place user selected.
   - [x] based on the coordinates (latitude and longitude) searched placed, place a marker on the map

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
