### ISSUE TITLE
Feature 6: User can view the photos uploaded

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the photos uploaded

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can also add photos taken at the place visited by clicking the view photo button. once clicked, will show modal with uploaded photos.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/191327630-7e290544-3de5-498d-bc0a-a2001b1157d9.png)
![image](https://user-images.githubusercontent.com/106636383/191327742-28df8573-30fe-4a63-a67b-b94cd455206c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] first need to do the backend first, do a get request
   - [x] check if response is what i expected
- [x] start coding for the client side, probably create a  new component for viewing the photos with modal.
- [x] style the modal for photos like figma
   - [x] need to deal with different photo types, portrait and landscape

### ☁️ Server Tasks

- [x] Update `server/index.js` to get the image from photos table
   - [x] for the matching logId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create/update a component to fetch the images from photos table
- [x] need to first get the logId, based on the logId grab all the photos related to it.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
