### ISSUE TITLE
Feature 2: User can create a log entry for the place

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a log entry for the place

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the marker is in place and clicked on the marker, a textbox will appear so the user can log an entry, can save, or cancel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/189774995-a2fcba4b-6ad7-4a08-ad24-08a8614d915c.png)
![image](https://user-images.githubusercontent.com/106636383/189775052-19877a85-c0c5-412e-b9c5-06facaf8e72b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] need a save button.
   - [x] will have a textarea to write a log
   - [x] user can cancel out of the textarea
   - [x] user can save the log by selecting the check box
      - [x]  once log check box clicked, will save information to database
      - [x] first will save location, latitude, and longitude of the locations table
      - [x] then in the logs table, will save the log, and will get locationId and location from locations table.

### 🐘 Database Tasks

- [x]  createdb travelJournal
- [x] create table "public"."logs" with it's fields
- [x] pre-populated data to see if it will create.

### ☁️ Server Tasks

- [x] Need to be able to post the log and the location.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
