### ISSUE TITLE
Feature 3: User can view their saved places on a map 

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their saved places on a map 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can view all the markers on a map. markers will represent the places that they saved.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/189776131-24056ee6-e67c-40d0-9f01-6bcd883e8cc4.png)
![image](https://user-images.githubusercontent.com/106636383/189776155-34a03832-0af0-4c5c-ad2d-0227107bdc36.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] need to research on how to us the API's Marker component.
- [x] need to figure out how to save the info in current component (saving logs) to concat to the collection of logs from parent component. so that previously saved and the currently save log will have markers saved

### ☁️ Server Tasks

- [x] Update `server/index.js` to get all saved data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to fetch the data from server
   - [x] fetched data will be stored in an array.
   - [x] based on the information in the array (lat, lng), markers will be placed using Marker component.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
