### ISSUE TITLE
Feature 4: User can view the log entry information for a place on the map

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view the log entry information for a place on the map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

once clicked on the marker they save a log entry, use can view what they had logged.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/190949833-74cd1c61-c8ae-4986-9586-1486c23f6a06.png)
![image](https://user-images.githubusercontent.com/106636383/190949871-faf60eba-fabe-43f6-937d-4c9c0c9e98ea.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] do the server side first, need to get the wanted log with the logId.
- [x] after testing with the HTTPie, need to work on the client side.
- [x] need to make the Marker clickable, once clicked need to be able to get the logId/id.
- [x] once getting the correct id, do a fetch request to get the info for that logId/id
- [x] need more research on Marker and its props/methods
- [x] might possiblely use infoWindow, if so, need research on infoWindow

### ☁️ Server Tasks

- [x] Update `server/index.js` to get a specific log, based on the logId.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create/Update component to get a log based on the logId
- [x] need to know how to select the logId to do a fetch.
- [x] once gotten the correct log, need to show the log that corresponds to the logId.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
