### ISSUE TITLE
Feature 5: User can include photo in their log entry

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can include photo in their log entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user clicks on the marker and the log is saved, it will have a section for choosing a photo to upload, once a file is selected, can upload.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106636383/191094708-9e3e7e4e-e78f-4b93-8a39-6764b2152351.png)
![image](https://user-images.githubusercontent.com/106636383/191095246-1b0bf00c-8839-4bfb-8e16-236a2466a3b1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] review FormData and refer back to the uploads exercise.
- [x] component for the photos, will be a modal
   - [x] similar to the modal when user logs an entry, but with a file upload

### 🐘 Database Tasks

- [x] Update `data.sql` to prepopulate the data for table photos

### ☁️ Server Tasks

- [x] Update `server/index.js` to post the photos
- [x] Check if the data is being posted correctly
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create/update a component to for adding a button for add photo
- [x] Use the form element, and in the method that uplaods photos, need prevent default and FormData
- [x] CreateRef for the file input.
- [x] use the fetch to send POST request, and body should be a form data object (not a JSON string)
- [x] once the result is received set null to the file input ref value.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
